logging:
  level:
    ROOT: INFO
    com.xiao9: INFO

server:
  port: 8888

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:xiao9;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: dev
    password:
    hikari:
      poolName: Hikaris
      auto-commit: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
  jpa:
    show-sql: true

springfox:
  documentation:
    enabled: true